INSERT into korisnik(user_id,email,ime,lozinka, prezime, potvrdjen,odobrenOdAdmina)values (1,'1','1','swPQNMuG2bPB+gomyKJuuAnliiuoDx6k+5vTjGx9lrl2mr6UFFeXIZCwPWJYBnVMo3EE1xUYBXNg/kxRt81fV6k=n4SHMZCgPEL1yLSz/Qm0J7a3e7kkD6/muGiLE0Fckg==','1', true,true)
INSERT into korisnik(user_id,email,ime,lozinka, prezime, potvrdjen,odobrenOdAdmina)values (2,'2','1','swPQNMuG2bPB+gomyKJuuAnliiuoDx6k+5vTjGx9lrl2mr6UFFeXIZCwPWJYBnVMo3EE1xUYBXNg/kxRt81fV6k=n4SHMZCgPEL1yLSz/Qm0J7a3e7kkD6/muGiLE0Fckg==','1', true,true)
INSERT into korisnik(user_id,email,ime,lozinka, prezime, potvrdjen,odobrenOdAdmina)values (3,'3','1','swPQNMuG2bPB+gomyKJuuAnliiuoDx6k+5vTjGx9lrl2mr6UFFeXIZCwPWJYBnVMo3EE1xUYBXNg/kxRt81fV6k=n4SHMZCgPEL1yLSz/Qm0J7a3e7kkD6/muGiLE0Fckg==','1', true,true)
insert into uloga(id,naziv)values(1,'ROLE_ADMIN')
insert into uloga(id,naziv)values(2,'ROLE_SUPERADMIN')
insert into uloga(id,naziv)values(3,'ROLE_MUSTERIJA')
insert into korisnik_uloge(korisnik_list_user_id,uloge_id)values(1,1)
insert into korisnik_uloge(korisnik_list_user_id,uloge_id)values(2,2)
insert into korisnik_uloge(korisnik_list_user_id,uloge_id)values(3,3)